### ISSUE TITLE
Not work chroot

### ISSUE THREAD

**Issue by grig27** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#13]
Option ChrootDirectory ignored.

File config omv_sftp_config.

`
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 120
StrictModes yes
PubkeyAuthentication yes
IgnoreRhosts yes
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
AcceptEnv LANG LC_*
Subsystem sftp internal-sftp -l INFO
UsePAM yes
Port 222
PermitRootLogin yes
Compression yes
PasswordAuthentication yes
PubkeyAuthentication no
AuthorizedKeysFile .ssh/authorized_keys .ssh/authorized_keys2 /var/lib/openmediavault/ssh/authorized_keys/%u

AddressFamily any
AllowGroups sftp-access
Match Group sftp-access
  ChrootDirectory /sftp/%u
  X11Forwarding no
  AllowTcpForwarding no
  ForceCommand internal-sftp -l INFO
`

On connect at auth.log.

`
Aug 24 11:01:26 grighomesrv sshd[6470]: Accepted password for backupusr from 192.168.2.47 port 64871 ssh2
Aug 24 11:01:26 grighomesrv sshd[6470]: pam_unix(sshd:session): session opened for user backupusr by (uid=0)
Aug 24 11:01:26 grighomesrv systemd-logind[896]: New session 13 of user backupusr.
Aug 24 11:01:26 grighomesrv systemd: pam_unix(systemd-user:session): session opened for user backupusr by (uid=0)
Aug 24 11:01:27 grighomesrv sshd[6506]: fatal: bad ownership or modes for chroot directory component "/"
Aug 24 11:01:27 grighomesrv sshd[6470]: pam_unix(sshd:session): session closed for user backupusr
`

**Comment by ryecoaaron** [comment]
The last message tells you what is wrong and it isn't caused by the plugin.  OMV 5.x should fix this automatically.  chmod 755 /

**Comment by grig27** [comment]
> The last message tells you what is wrong and it isn't caused by the plugin. OMV 5.x should fix this automatically. chmod 755 /

All work! I set chmod 777 / ....

**Comment by ryecoaaron** [comment]
You should never set / to 777.
