### ISSUE TITLE
add user fails

### ISSUE THREAD

**Issue by scascalesp** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#14]
When user has rwe permissions instead of rw fails
![image](https://user-images.githubusercontent.com/89306506/132527515-1e026018-624e-4859-9f8e-4ab9d9630098.png)
I can add more users for sftp but its great can be fixed

Thx

**Comment by ryecoaaron** [comment]
The privileges aren't at the OS level.  You need to give the user privileges at the shared folder level in the Shared Folder tab.  There is no execute option in the Shared Folder privileges.

**Comment by scascalesp** [comment]
IN ACL you have this options
![image](https://user-images.githubusercontent.com/89306506/132671693-a5c116cf-3fc9-4fca-8b20-8971aa995f1e.png)

**Comment by ryecoaaron** [comment]
Yep but the plugin does not use ACLs. It strictly uses Shared Folder privileges. ACLs actually change the filesystem. Shared folder privileges are meant to be used with other plugins like samba and sftp.
