### ISSUE TITLE
Issue with permission

### ISSUE THREAD

**Issue by g2ufo** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#17]
I am trying to configure the SFTP plugin on omv6, but when adding a folder, an error about deficiency of rights: 500 - Internal Server Error
'User' Does Not Have Read Only or Read / Write Privileges to this Shared Folder. 
But linux shows other:

drwxrws---+  2 user users    2 Jan 30 16:44 Folder

**Comment by ryecoaaron** [comment]
You must give the user those permissions to the sharedfolder in the omv web interface. It is not checking the permissions at the OS level.

**Comment by g2ufo** [comment]
Yes, i give the user those permissions to the sharedfolder in the omv web interface.

**Comment by ryecoaaron** [comment]
Is the user's name actually 'user'?  Can you show me a screenshot of the user's permissions for the sharedfolder you are trying to use with sftp?

**Comment by g2ufo** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/51451549/151833145-f4402df5-3e8c-4402-9769-44a001df8e9c.jpg)
I select exactly the same user as in the screenshot in the sftp plugin settings. 
A similar error occurs if  i grant rights to any other user.

**Comment by ryecoaaron** [comment]
You are using ACLs.  You must use privileges.

**Comment by g2ufo** [comment]
Hmm, but at the bottom of the page are the owner and group, which are UNIX permissions. and on the top - ACL. 
Linux console said
drwxrws---+ 2 user users 2 Jan 30 16:44 Folder - is it unix permission?

**Comment by ryecoaaron** [comment]
The plugin does not use ACL or the filesystem permissions.  It looks in the OMV database for sharefolder privileges.  So, it does not matter what the ACL dialog or the console shows you.

**Comment by g2ufo** [comment]
Is this implemented only for the sftp plugin or for some others? I just don't understand why we need one more privileges in the OMV database if there are already POSIX and ACLs...

**Comment by ryecoaaron** [comment]
I actually don't think ACLs are used for anything in OMV.  They only make the ACL changes at the filesystem level.  Everything else uses privileges (ftp, sftp, samba, etc) because privileges is how OMV and services work. I hate ACLs personally.

There needs to be a separate database of privileges.   Samba is the biggest user.  How would you give a user access to a samba share (which is a folder and all sub folders) if you didn't have their explicit permissions in the database?

**Comment by g2ufo** [comment]
ACL its like Windows permission with folder and subfolder privileges, but in linux filesystem. 
1) create sharefolder with POSIX permission 750 for examle
2) create users
3) add the appropriate ACL rights to users. It is a filesystem level. And samba works perfect with it.

Perhaps I should reconsider my attitude to the permissions ACL?It is not good?

**Comment by ryecoaaron** [comment]
I'm well aware of what ACLs are.  I've run a samba server for 20+ years without them though.  And while your permissions "work" when using ACLs, they are kind of going around how samba translates permissions to linux filesystems.  The samba config has user and group access parameters to do this and that is how OMV configures it.

If you ask me, no one should ever use ACLs (except if you use selinux).  I want to see all permissions when I use ls -al.  I don't want to have to use get/setfacl.  But you can use what you want.  ACLs just won't work for the sftp plugin configuration.

**Comment by g2ufo** [comment]
Many thanks for the clarification!
