### ISSUE TITLE
SFTP seems to block the insertion of NFS share

### ISSUE THREAD

**Issue by IridiumXOR** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#4]
I try to create an NFS share (named tftp), with default option but when i try to
save the configuration i obtain:

Failed to execute command 'export
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export
LANG=C; omv-mkconf sftp 2>&1' with exit code '32': mount: mount point
/export/tftp does not exist

Errore #0: exception 'OMV\ExecException' with message 'Failed to execute command
'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin;
export LANG=C; omv-mkconf sftp 2>&1' with exit code '32': mount: mount point
/export/tftp does not exist' in
/usr/share/php/openmediavault/system/process.inc:175 Stack trace: #0
/usr/share/openmediavault/engined/module/sftp.inc(66):
OMV\System\Process->execute() #1
/usr/share/openmediavault/engined/rpc/config.inc(163):
OMVModuleSftp->applyConfig() http://bugtracker.openmediavault.org/view.php?id=2
[internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
http://bugtracker.openmediavault.org/view.php?id=3
/usr/share/php/openmediavault/rpc/serviceabstract.inc(124):
call_user_func_array(Array, Array)
http://bugtracker.openmediavault.org/view.php?id=4
/usr/share/php/openmediavault/rpc/serviceabstract.inc(150):
OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
http://bugtracker.openmediavault.org/view.php?id=5
/usr/share/php/openmediavault/rpc/serviceabstract.inc(528):
OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus5t...',
'/tmp/bgoutputZH...') http://bugtracker.openmediavault.org/view.php?id=6
/usr/share/php/openmediavault/rpc/serviceabstract.inc(151):
OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
http://bugtracker.openmediavault.org/view.php?id=7
/usr/share/openmediavault/engined/rpc/config.inc(208):
OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
http://bugtracker.openmediavault.org/view.php?id=8 [internal function]:
OMVRpcServiceConfig->applyChangesBg(Array, Array)
http://bugtracker.openmediavault.org/view.php?id=9
/usr/share/php/openmediavault/rpc/serviceabstract.inc(124):
call_user_func_array(Array, Array)
http://bugtracker.openmediavault.org/view.php?id=10
/usr/share/php/openmediavault/rpc/rpc.inc(86):
OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
http://bugtracker.openmediavault.org/view.php?id=11 /usr/sbin/omv-engined(536):
OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
http://bugtracker.openmediavault.org/view.php?id=12 {main}

**Comment by ryecoaaron** [comment]
This is a bug in the nfs plugin where is doesn't create the /export/ directory.

**Comment by votdev** [comment]
Please point me to the code where this happens. I can not reproduce this when i create a NFS share.

**Comment by ryecoaaron** [comment]
I thought maybe he was still running a pre-3.0.66 version affected by this - http://bugtracker.openmediavault.org/view.php?id=1697

**Comment by IridiumXOR** [comment]
No, I'm using 3.0.69
here the bug into OMV bug tracker `http://bugtracker.openmediavault.org/view.php?id=1697`

**Comment by disrupted** [comment]
I am receiving the same error when trying to create new NFS shares. why was this issue closed?

**Comment by ryecoaaron** [comment]
I guess I thought it was fixed.  Should be fixed in 3.1.5.
