### ISSUE TITLE
Granting access only for members of sftp-access

### ISSUE THREAD

**Issue by 3ed** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#5]
```
AllowGroups sftp-access
```
before `Match` block

**Comment by ryecoaaron** [comment]
Plugin works for me.  Why is AllowGroups needed?

**Comment by 3ed** [comment]
`Match` set this accounts to chroot but any other user (non in sftp-access group) will be set to home directory or /. Default of OMV is to set: chown root:users and chmod 775 on shared folders. If you not in sftp-access you can go to /srv/dir/share and read/write to this share. AllowGroups denie all access for users who are not in group sftp-access.


https://linux.die.net/man/5/sshd_config

**Comment by ryecoaaron** [comment]
I get it but I don't think either way is wrong.  Some might think that if I'm not in the sftp-access group, I have access to the normal ssh port.  Why should the sftp port have different or no access?  It is should probably be selectable with a checkbox called AllowGroups - Allow access to only members of the sftp-access group.  I will look at what it would take to add this.

**Comment by 3ed** [comment]
This service have name sftp not ssh. Suggests that this is another file server like ftp(s).

I wonder if things like port tunneling still works. Shouldn't? On file server... With ChrootDirectory, etc... I don't test this.

> I will look at what it would take to add this.

Great. :)

**Comment by ryecoaaron** [comment]
But the service is sftp not really ssh and definitely ftps.  It is appropriately named.

In the next version, I will explicitly disable tunneling and x11 forwarding.

**Comment by ryecoaaron** [comment]
Fix has been committed but I need to test.

**Comment by ryecoaaron** [comment]
Fixed in 3.1
