### ISSUE TITLE
Second shared folder for user not added to fstab

### ISSUE THREAD

**Issue by jkelly99** [OpenMediaVault-Plugin-Developers/openmediavault-sftp#9]
Currently have shared folder 'share1' for 'user1' and all works correctly. When I add 'share2' for 'user1' 'share2' does not appear in /sftp/user1/ nor in fstab. I have tried removing and adding from the control panel multiple times as well as several reboots.

Currently I have manually added an entry for 'share2' in fstab and all is working. Bug or am I doing something incorrectly?

**Comment by ryecoaaron** [comment]
I use this plugin and it is working well on my systems.  What is the output of:  omv-showkey sftp

**Comment by jkelly99** [comment]
<sftp>
      <enable>1</enable>
      <port>222</port>
      <passwordauthentication>1</passwordauthentication>
      <pubkeyauthentication>1</pubkeyauthentication>
      <allowgroups>1</allowgroups>
      <extraoptions></extraoptions>
      <shares>
        <share>
          <uuid>9c6bd5fd-431a-49db-ba9a-df3d665e8d99</uuid>
          <sharedfolderref>58a01a29-427c-4bcf-a8bc-266a49eb4182</sharedfolderref>
          <username>user1</username>
        </share>
        <share>
          <uuid>43454279-405e-4f47-b34b-03664738da52</uuid>
          <sharedfolderref>5a0504e3-eacc-497e-9a3b-0ca7d8cbc599</sharedfolderref>
          <username>user1</username>
        </share>
      </shares>
    </sftp>


This is with the current setup of my manually edited fstab. Is this useful? Should I remove my fstab edits and run again?

**Comment by ryecoaaron** [comment]
I don't see any problems with that.  Does omv-mkconf fstab fix your fstab?  This command will revert your changes.

**Comment by jkelly99** [comment]
I'll give omv-mkconf a try when I can and report back. I don't have access to the omv machine for a while and don't want to try messing with fstab remotely. :)
